package edu.intech.intflix.controller;

import edu.intech.intflix.model.Episode;
import edu.intech.intflix.model.EpisodeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path="/api") // This means URL's start with /api (after Application path)
public class EpisodeController {
    @Autowired  // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EpisodeRepository episodeRepository;

    @PostMapping(path = "/episode") // Map ONLY POST Requests
    public @ResponseBody
    void addNewSeries(@RequestBody Episode episode) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        episodeRepository.save(episode);
    }

    @GetMapping(path = "/episode")
    public @ResponseBody
    Iterable<Episode> getAllSeries() {
        // This returns a JSON or XML with the users
        return episodeRepository.findAll();
    }

    @DeleteMapping(path = "/episode")
    public @ResponseBody
    void deleteUser(@RequestParam Long id) {
        Optional<Episode> series = episodeRepository.findById(id);
        series.ifPresent(episodeRepository::delete);
    }
}