package edu.intech.intflix.controller;

import edu.intech.intflix.model.Series;
import edu.intech.intflix.model.SeriesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path="/api") // This means URL's start with /api (after Application path)
public class SeriesController {
    @Autowired  // This means to get the bean called userRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private SeriesRepository seriesRepository;

    @PostMapping(path = "/series") // Map ONLY POST Requests
    public @ResponseBody
    void addNewSeries(@RequestBody Series series) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        seriesRepository.save(series);
    }

    @GetMapping(path = "/series")
    public @ResponseBody
    Iterable<Series> getAllSeries() {
        // This returns a JSON or XML with the users
        return seriesRepository.findAll();
    }

    @DeleteMapping(path = "/series")
    public @ResponseBody
    void deleteUser(@RequestParam Long id) {
        Optional<Series> series = seriesRepository.findById(id);
        series.ifPresent(seriesRepository::delete);
    }
}
